apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: half-hour-cis-results
  labels:
    deployment: production
spec:
  reportType: cis-benchmark
  schedule: '*/30 * * * *'
  cis:
    highThreshold: 100
    medThreshold: 50
    includeUnscoredTests: true
    numFailedTests: 5
